apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: d76b87cd-9683-4dbc-a745-ecf3c33a1af5
    subject: ab-mem-catalogue-sep18_litmus
    workflow_id: 3ebcb093-48a8-42fe-bf22-0d02bf53a185
    workflows.argoproj.io/controller-instanceid: d76b87cd-9683-4dbc-a745-ecf3c33a1af5
  name: ab-mem-catalogue-sep18-1631989111
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: run-benchmark
        template: run-benchmark
      - arguments: {}
        name: pod-memory-hog
        template: pod-memory-hog
  - arguments: {}
    container:
      args:
      - kubectl apply -f /tmp/pod-memory-hog.yaml -n {{workflow.parameters.adminModeNamespace}} |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-memory-hog
        path: /tmp/pod-memory-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Injects memory consumption on pods belonging to an app deployment
            kind: ChaosExperiment
            metadata:
              name: pod-memory-hog
              labels:
                name: pod-memory-hog
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.0.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                      - batch
                      - apps
                      - apps.openshift.io
                      - argoproj.io
                      - litmuschaos.io
                    resources:
                      - jobs
                      - pods
                      - pods/log
                      - replicationcontrollers
                      - deployments
                      - statefulsets
                      - daemonsets
                      - replicasets
                      - deploymentconfigs
                      - rollouts
                      - pods/exec
                      - events
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                      - deletecollection
                image: litmuschaos/go-runner:2.0.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-memory-hog
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: MEMORY_CONSUMPTION
                    value: "500"
                  - name: NUMBER_OF_WORKERS
                    value: "1"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: RAMP_TIME
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: LIB_IMAGE
                    value: litmuschaos/go-runner:2.0.0
                  - name: STRESS_IMAGE
                    value: alexeiled/stress-ng:latest-ubuntu
                  - name: CONTAINER_RUNTIME
                    value: containerd
                  - name: SOCKET_PATH
                    value: /run/containerd/containerd.sock
                  - name: SEQUENCE
                    value: parallel
                  - name: TARGET_PODS
                    value: ""
                labels:
                  name: pod-memory-hog
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.0.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-pod-memory-hog.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-memory-hog
        path: /tmp/chaosengine-pod-memory-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-memory-hog
              labels:
                instance_id: c5f822a4-bbea-40e5-9a88-f82b51ae51a8
                context: pod-memory-hog_litmus
                workflow_name: ab-mem-catalogue-sep18-1631989111
            spec:
              appinfo:
                appns: sock-shop
                applabel: name=catalogue
                appkind: deployment
              jobCleanUpPolicy: retain
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-memory-hog
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: MEMORY_CONSUMPTION
                          value: "100"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                        - name: CONTAINER_RUNTIME
                          value: containerd
                        - name: SOCKET_PATH
                          value: /run/containerd/containerd.sock
                    probe:
                      - name: cmdProbeTest
                        type: cmdProbe
                        mode: EOT
                        runProperties:
                          probeTimeout: 5
                          retry: 2
                          interval: 5
                          initialDelaySeconds: 2
                          stopOnFailure: false
                        cmdProbe/inputs:
                          command: kubectl get pods -n litmus
                            -o  jsonpath='{.items[?(@.metadata.labels.app=="tenant-bench")].metadata.name}'
                            | xargs kubectl logs -n litmus |awk '/longest/ {print $2}'
                          source: inline
                          comparator:
                            type: int
                            criteria: <
                            value: "1000"
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-memory-hog
    outputs: {}
  - arguments: {}
    container:
      args:
      - kubectl create -f /tmp/bench.yaml -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: lachlanevenson/k8s-kubectl
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: run-benchmark
        path: /tmp/bench.yaml
        raw:
          data: |
            apiVersion: batch/v1
            kind: Job
            metadata:
              generateName: tenant-bench
              labels:
                app: tenant-bench
            spec:
              template:
                metadata:
                  labels:
                    app: tenant-bench
                spec:
                  restartPolicy: Never
                  containers:
                    - args:
                        - -c
                        - /go/bin/main -r -c 1 -t 120 -n 1000
                          http://catalogue.sock-shop/catalogue; exit 0
                      command:
                        - /bin/sh
                      image: devth/alpine-bench
                      imagePullPolicy: Always
                      name: nginx-bench
    metadata: {}
    name: run-benchmark
    outputs: {}
status:
  finishedAt: null
  startedAt: null
