apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: d76b87cd-9683-4dbc-a745-ecf3c33a1af5
    subject: custom-chaos-workflow_litmus
    workflow_id: 18950489-e52f-4c20-aba6-d90fcf3f59e3
    workflows.argoproj.io/controller-instanceid: d76b87cd-9683-4dbc-a745-ecf3c33a1af5
  name: custom-chaos-workflow-1632310147
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-delete
        template: pod-delete
  - arguments: {}
    container:
      args:
      - kubectl apply -f /tmp/pod-delete.yaml -n {{workflow.parameters.adminModeNamespace}} |  sleep 30
      command:
      - sh
      - -c
      image: litmuschaos/k8s:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Deletes a pod belonging to a deployment/statefulset/daemonset
            kind: ChaosExperiment
            metadata:
              name: pod-delete
              labels:
                name: pod-delete
                app.kubernetes.io/part-of: litmus
                app.kubernetes.io/component: chaosexperiment
                app.kubernetes.io/version: 2.0.0
            spec:
              definition:
                scope: Namespaced
                permissions:
                  - apiGroups:
                      - ""
                      - apps
                      - apps.openshift.io
                      - argoproj.io
                      - batch
                      - litmuschaos.io
                    resources:
                      - deployments
                      - jobs
                      - pods
                      - pods/log
                      - replicationcontrollers
                      - deployments
                      - statefulsets
                      - daemonsets
                      - replicasets
                      - deploymentconfigs
                      - rollouts
                      - pods/exec
                      - events
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                      - deletecollection
                image: litmuschaos/go-runner:2.0.0
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name pod-delete
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "5"
                  - name: RAMP_TIME
                    value: ""
                  - name: FORCE
                    value: "true"
                  - name: CHAOS_INTERVAL
                    value: "1"
                  - name: PODS_AFFECTED_PERC
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: TARGET_PODS
                    value: ""
                  - name: SEQUENCE
                    value: parallel
                labels:
                  name: pod-delete
                  app.kubernetes.io/part-of: litmus
                  app.kubernetes.io/component: experiment-job
                  app.kubernetes.io/version: 2.0.0
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-pod-delete.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/chaosengine-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              namespace: "{{workflow.parameters.adminModeNamespace}}"
              generateName: pod-delete
              labels:
                instance_id: d1adf9e5-4fd5-47bb-9094-903c6d84cf06
                context: pod-delete_litmus
                workflow_name: custom-chaos-workflow-1632310147
            spec:
              appinfo:
                appns: sock-shop
                applabel: name=catalogue
                appkind: deployment
              jobCleanUpPolicy: retain
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "5"
                        - name: CHAOS_INTERVAL
                          value: "1"
                        - name: FORCE
                          value: "false"
                        - name: PODS_AFFECTED_PERC
                          value: ""
                    probe:
                      - name: http
                        type: httpProbe
                        mode: EOT
                        runProperties:
                          probeTimeout: 2
                          retry: 1
                          interval: 2
                          initialDelaySeconds: 1
                          stopOnFailure: false
                        httpProbe/inputs:
                          url: http://catalogue.sock-shop/catalogue
                          insecureSkipVerify: true
                          responseTimeout: 1000
                          method:
                            get:
                              criteria: ==
                              responseCode: "200"
              annotationCheck: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-delete
    outputs: {}
status:
  finishedAt: null
  startedAt: null
